name: Mend

on:
  workflow_call:
    secrets:
      WS_URL:
        required: false
      WS_APIKEY_NGINX:
        required: false
      WS_USER_KEY:
        required: false
      WS_COMPLIANCE_THRESHOLD:
        required: false
    inputs:
      product_name:
        type: string
        required: false
      project_name:
        required: false
        type: string

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  scan:
    if: ${{ ( github.repository_owner == 'nginx' || github.repository_owner == 'nginxinc' ) }}
    name: Mend
    runs-on: ubuntu-24.04
    steps:
      - name: Decommission message
        run: echo "WARNING! Mend is deprecated. Migrate to Semgrep."
